Repository geekquad/Image-Processing-OpenCV, pull requests merged in 2021-05, with the labels that each got.

#214 Image-Registration
  ImageRegistration/.ipynb_checkpoints/ImageRegistration-checkpoint.ipynb
  ImageRegistration/ImageRegistration.ipynb
  ImageRegistration/README.md
  ImageRegistration/images/dist_img1.jpg
  ImageRegistration/images/distor_img.JPG
  ImageRegistration/images/img_reg.JPG
  ImageRegistration/images/match_img.JPG
  ImageRegistration/images/ref_img.JPG
  ImageRegistration/images/reference_img.jpg
  ImageRegistration/images/reg_img.JPG
Labels: Level3, gssoc21

#203 Denoising algorithm
  Denoising Algorithm/Denoising_Algorithm.ipynb
  Denoising Algorithm/Input.png
  Denoising Algorithm/Output.png
  Denoising Algorithm/Readme.md
Labels: Level3, gssoc21

#216 Bilateral filter
  ImageSmoothing/BilateralSmoothing/Bilateral_Smoothing.ipynb
  ImageSmoothing/BilateralSmoothing/README.md
  ImageSmoothing/BilateralSmoothing/images/1.jpg
  ImageSmoothing/BilateralSmoothing/images/2.jpg
  ImageSmoothing/BilateralSmoothing/images/3.jpg
  ImageSmoothing/BilateralSmoothing/images/Gaussian_noise.jpg
  ImageSmoothing/BilateralSmoothing/images/gauss1.JPG
  ImageSmoothing/BilateralSmoothing/images/gauss2.JPG
  ImageSmoothing/BilateralSmoothing/images/img1.JPG
  ImageSmoothing/BilateralSmoothing/images/img2.JPG
Labels: Level3, gssoc21

#106 Contour Detection
  ContourDetection/ContourDetection.ipynb
  ContourDetection/README.md
  ContourDetection/images/Binary_Image.png
  ContourDetection/images/Contours.png
  ContourDetection/images/Gray_Image.png
  ContourDetection/images/demo1.png
  ContourDetection/images/demo2.png
Labels: Level3, gssoc21

#215 Brute force feature matcher implementation
  BruteForceFeatureMatcher/BruteForceFeatureMatcher.ipynb
  BruteForceFeatureMatcher/README.md
Labels: Level3, gssoc21

#225 Added Files for Homography and Feature Matching
  Homography_FeatureMatching/Homography.ipynb
  Homography_FeatureMatching/Images/hp1.jpg
  Homography_FeatureMatching/Images/hp2.png
  Homography_FeatureMatching/Images/hp3.jpg
  Homography_FeatureMatching/Images/hp_all.jpg
  Homography_FeatureMatching/README.md
Labels: Level3, gssoc21

#229 Implemented Hough circles for issue #56
  HoughTransformation/hough_circle_transform.ipynb
Labels: Level3, gssoc21

#231 added the code ,image and readme file in Color Detection Folder
  Color Detection/README.md
  Color Detection/color__detection.ipynb
  Color Detection/images/flower.jfif
  Color Detection/images/green colour detected.png
  Color Detection/images/mask over green regions.png
Labels: Level3, gssoc21

#240 Implemented Image Blending for issue#63
  ImageBlending/image_blending.ipynb
Labels: Level3, gssoc21

#232 Illuminating Night Images
  Improving_Illumination/.gitignore
  Improving_Illumination/Illuminating_Dark_Images.ipynb
  Improving_Illumination/README.md
  Improving_Illumination/images/test1.jpg
  Improving_Illumination/images/test2.jpg
  Improving_Illumination/images/test3.jpg
  Improving_Illumination/output/out1.jpg
  Improving_Illumination/output/out2.jpg
  Improving_Illumination/output/out3.jpg
Labels: Level3, gssoc21

#236 Depth map completed
  DepthMap/Depth_Map.ipynb
  DepthMap/README.md
  DepthMap/left.jpg
  DepthMap/output.png
  DepthMap/right.jpg
  GeometericalShapes/Geometerical_shapes.ipynb
  GeometericalShapes/README.md
  GrayLevelSlicingWithoutBackground/Gray_level_slicing_without_background.ipynb
  GrayLevelSlicingWithoutBackground/README.md
Labels: Level3, gssoc21

#253 Added Ipython script for averaging smoothing for issue#245
  ImageSmoothing/Averaging_smoothing.ipynb
Labels: Level3, gssoc21

#262 #218 Fourier Transformation
  FourierTransformation/Fourier_Transformation.ipynb
  FourierTransformation/input/a_0.png
  FourierTransformation/input/a_1.png
  FourierTransformation/input/a_2.png
  FourierTransformation/input/b_0.png
  FourierTransformation/input/b_1.png
  FourierTransformation/input/b_2.png
  FourierTransformation/input/c_0.png
  FourierTransformation/input/c_1.png
  FourierTransformation/input/c_2.png
  FourierTransformation/readme.md
Labels: Level3, gssoc21

#270 Piecewise Linear Transformation
  PiecewiseLinearTransformation/Piecewise_Linear_Transformation.ipynb
  PiecewiseLinearTransformation/README.md
Labels: Level2, gssoc21

#277 added code and dependencies for CLAHE algorithm
  CLAHE Algorithm/CLAHE.ipynb
  CLAHE Algorithm/README.md
  CLAHE Algorithm/images/clahe_input.png
  CLAHE Algorithm/images/clahe_input1.png
  CLAHE Algorithm/images/clahe_output.png
  CLAHE Algorithm/images/clahe_output1.png
  CLAHE_Algorithm/CLAHE.ipynb
  CLAHE_Algorithm/README.md
  CLAHE_Algorithm/images/clahe_input.png
  CLAHE_Algorithm/images/clahe_input1.png
  CLAHE_Algorithm/images/clahe_output.png
  CLAHE_Algorithm/images/clahe_output1.png
Labels: Level3, gssoc21

#199 Arithmetic operations on images
  Arithmetic Operations on Images/ImageAddition.ipynb
  Arithmetic Operations on Images/Images/FinalAdd.png
  Arithmetic Operations on Images/Images/FinalSub.png
  Arithmetic Operations on Images/Images/circle1.jpg
  Arithmetic Operations on Images/Images/cosmic1.jpg
  Arithmetic Operations on Images/Images/nature.jpg
  Arithmetic Operations on Images/Images/pattern1.jpg
  Arithmetic Operations on Images/README.md
  Arithmetic Operations on Images/subtractImages.ipynb
Labels: Level3, gssoc21

#278 For Scharr Transformation, Gray level slicing, Laplacian edge detection, Log transformation
  EdgeDetection/Laplacian_Edge_Detection.ipynb
  GrayLevelSlicing/Gray_Level_Slicing_With_Background.ipynb
  GrayLevelSlicing/Gray_level_slicing_without_background.ipynb
  GrayLevelSlicing/README.md
  LogTransformation/Log_Transformation.ipynb
  LogTransformation/README.md
  ScharrTransformation/README.md
  ScharrTransformation/Scharr_Transformation.ipynb
Labels: Level3, gssoc21

#281 Added code and dependencies for Image Rotation
  ImageResize/Image_Rotation/Image_Rotation.ipynb
  ImageResize/Image_Rotation/Rotated.png
  ImageResize/Image_Rotation/input.png
  ImageResize/Readme.md
Labels: Level3, gssoc21

#282 Added code and dependencies for Sift Algorithm
  SiftAlgorithm/README.md
  SiftAlgorithm/Sift_Algorithm.ipynb
  SiftAlgorithm/Sifted_charlie.png
  SiftAlgorithm/charlie.jpg
Labels: Level3, gssoc21

#283 Added Image cropping technique for issue#252
  ImageCropping/image_cropping.ipynb
Labels: Level3, gssoc21

#280 Added code and dependencies for Image Translation.
  ImageResize/Image_Translation/Image_Translation.ipynb
  ImageResize/Image_Translation/Translated.png
  ImageResize/Image_Translation/input.jpg
  ImageResize/Readme.md
Labels: Under Review

#287 Added the code and dependencies for Image Closing
  ImageClosing/GRAY_input.png
  ImageClosing/Image_Closing.ipynb
  ImageClosing/README.md
  ImageClosing/closed.png
  ImageClosing/input.jpg
Labels: Level3, gssoc21

#293 Added files for convex hull
  Convex_Hull/README.md
  Convex_Hull/convex_hull.ipynb
  Convex_Hull/img3.jpg
Labels: Level3, gssoc21

#298 #274 Blob detection files added
  BlobDetector/BLOB Detection.ipynb
  BlobDetector/Input/sunflower.jpg
  BlobDetector/Output/Blob_Output.png
  BlobDetector/README.md
Labels: Level3, gssoc21

#299 #269 Flann Matcher files added
  Flann Matcher/FLANN Matcher.ipynb
  Flann Matcher/Input/many_cereals.jpg
  Flann Matcher/Input/reeses_puffs.png
  Flann Matcher/Output/FlannOutput.png
  Flann Matcher/README.md
Labels: Level3, gssoc21

#300 Bitwise operations in OpenCV
  BitwiseOperations/Bitwise.ipynb
  BitwiseOperations/README.md
Labels: Level3, gssoc21

#310 Added code and dependencies for Image Zooming
  ImageResize/Image_Zooming/Image_zooming.ipynb
  ImageResize/Image_Zooming/images/input.png
  ImageResize/Image_Zooming/images/zoomed.png
  ImageResize/Readme.md
Labels: Level2, gssoc21

#309 Added code and dependencies for Image Scaling
  ImageResize/Image_Scaling/Image_scaling.ipynb
  ImageResize/Image_Scaling/images/input.png
  ImageResize/Image_Scaling/images/scaled_down_x.png
  ImageResize/Image_Scaling/images/scaled_down_y.png
  ImageResize/Image_Scaling/images/scaled_up_x.png
  ImageResize/Image_Scaling/images/scaled_up_y.png
  ImageResize/Readme.md
Labels: Level2, gssoc21

#316 Added image pyramiding readme
  ImagePyramids/README.md
Labels: Level1, gssoc21

#320 Template matching OpenCV
  Template Matching/README.md
  Template Matching/TemplateMatching.ipynb
  Template Matching/rose.jpeg
  Template Matching/temp.jpeg
Labels: Level3, gssoc21

#323 Color Slicing
  ColorSlicing/Color_Slicing.ipynb
  ColorSlicing/Readme.md
Labels: Level3, gssoc21

#329 Added Probabilistic Hough Line Transformation [Part of #56]
  HoughTransformation/Probabilistic_Hough_Line_Transformation.ipynb
Labels: Level3, gssoc21

#331 added code and dependencies for Image flipping
  ImageFlipping/Image_Flipping.ipynb
  ImageFlipping/README.md
  ImageFlipping/images/GRAYSCALED_input.png
  ImageFlipping/images/horizontally_flipped.png
  ImageFlipping/images/input.png
  ImageFlipping/images/vertically_and_horizontally_flipped.png
  ImageFlipping/images/vertically_flipped.png
Labels: Level2, gssoc21

#333 Added code and dependencies for Image Shearing
  ImageShearing/Image_Shearing.ipynb
  ImageShearing/README.md
  ImageShearing/images/input.png
  ImageShearing/images/sheared_x-axis.png
  ImageShearing/images/sheared_y-axis.png
Labels: Level2, gssoc21

#334 Added Image Pixelation file
  ImagePixelation/.ipynb_checkpoints/Untitled-checkpoint.ipynb
  ImagePixelation/ImagePixelation.ipynb
  ImagePixelation/lotus.jpg
  ImagePixelation/original.PNG
  ImagePixelation/output.PNG
  ImagePixelation/readme.md
Labels: Level3, gssoc21

#322 Image Contrast Adjustment #312
  Image Contrast Adjustment/Image Contrast Adjustment_.ipynb
  Image Contrast Adjustment/Images/Original_image.jpg
  Image Contrast Adjustment/Images/Result.jpg
  Image Contrast Adjustment/README.md
Labels: Level3, gssoc21

#332 Camshift Algorithm Implementation
  Camshift/.ipynb_checkpoints/CamShift-checkpoint.ipynb
  Camshift/CamShift.ipynb
  Camshift/README.md
Labels: Level3, gssoc21

#336 ContoursHierarchy Files added
  ContoursHierarchy/ContoursHierarchy.ipynb
  ContoursHierarchy/Input/contoursHeirarchy.png
  ContoursHierarchy/Output/RETR_COMP.png
  ContoursHierarchy/Output/RETR_EXTERNAL.png
  ContoursHierarchy/Output/RETR_LIST.png
  ContoursHierarchy/Output/RETR_TREE.png
  ContoursHierarchy/README.md
Labels: Level3, gssoc21

#344 implemented Image Pyramiding for issue#263
  ImagePyramids/image_pyramiding.ipynb
Labels: Level3, gssoc21

#354 Update README.md
  AffineTransformation/README.md
Labels: Level1, gssoc21

#362 Create Readme.md
  EdgeDetection/CannyEdgeDetection/Readme.md
Labels: Level1, gssoc21

#356 Image sharpening
  Image Sharpening/Image_sharpening.ipynb
  Image Sharpening/README.md
  Image Sharpening/VT.jpg
Labels: Level3, gssoc21

#365 Implemented Nearest neighbor interpolation for issue#305 with required changes
  ImageResize/Nearest_Neighbor_Interpolation/nearest_neighbour_interpolation.ipynb
Labels: Level3, gssoc21

#363 Create Readme.md
  EdgeDetection/PrewittEdgeDetection/Readme.md
Labels: Level3, gssoc21

#368 Added code and dependencies for Shape Detection
  ShapeDetection/README.md
  ShapeDetection/images/input.jpg
  ShapeDetection/images/output.png
  ShapeDetection/shape_detector.ipynb
Labels: Level3, gssoc21

#380 Create Readme.md
  EdgeDetection/SobelEdgeDetection/Readme.md
Labels: Level1, gssoc21
