Repository geekquad/Image-Processing-OpenCV, pull requests merged in 2021-03, with the labels that each got.

#109 Update README.md
  README.md
Labels: Level 0, gssoc21

#74 Simple Image Thresholding
  SimpleThresholding/README.md
  SimpleThresholding/Simple_Thresholding.ipynb
  SimpleThresholding/test.png
Labels: Level 2, Reviewed, gssoc21

#80 Added the code for ConcatenateImages
  ConcatenateImages/Concatenate Images.ipynb
  ConcatenateImages/Readme.md
  ConcatenateImages/images/1.jpg
  ConcatenateImages/images/2.jpg
  ConcatenateImages/images/3.jpg
  ConcatenateImages/images/4.jpg
Labels: Level 3, Reviewed, gssoc21

#99 Added greeting bot
  .github/config.yml
Labels: Reviewed

#92 update contributing.md
  CONTRIBUTING.md
Labels: Level 2, gssoc21

#50 Adaptive thresholding
  AdaptiveThresholding/Adaptive.ipynb
  AdaptiveThresholding/README.md
  AdaptiveThresholding/Thresholding.png
  AdaptiveThresholding/img
  AdaptiveThresholding/ppp
Labels: Level 3, gssoc21

#51 Background subtractor
  BackgroundSubtraction/Background Subtractor.ipynb
  BackgroundSubtraction/README.md
  BackgroundSubtraction/requirements.txt
Labels: Level 3, gssoc21
