Repository geekquad/Image-Processing-OpenCV, pull requests merged in 2021-04, with the labels that each got.

#112 Image Ghostification
  Ghostification/ghostifying image.ipynb
  Ghostification/images/Ghostified image.jpg
  Ghostification/images/Image.jpg
  Ghostification/readme.md
Labels: Level 3, gssoc21

#168 Update README.md
  README.md
Labels: Level 0, gssoc21

#134 Issue 126 completed
  Morphological Transformations/Morphological Transformations.ipynb
  Morphological Transformations/README.md
  Morphological Transformations/assets/blackhat.png
  Morphological Transformations/assets/boatsnp.png
  Morphological Transformations/assets/circles.png
  Morphological Transformations/assets/closing.png
  Morphological Transformations/assets/j.png
  Morphological Transformations/assets/tophat.png
Labels: Level 3, gssoc21

#135 Perspective and Affine Transform
  AffineTransformation/Affine Transformation.ipynb
  AffineTransformation/OpenCV_Logo.png
  PerspectiveTransformation/perspective_demo.ipynb
  PerspectiveTransformation/perspective_demo_1.png
  PerspectiveTransformation/perspective_demo_2.png
  PerspectiveTransformation/perspective_transform.ipynb
  PerspectiveTransformation/test_image.png
Labels: Level3, gssoc21

#144 Histogram Matching
  HistogramMatching/Graph.png
  HistogramMatching/README.md
  HistogramMatching/empire_state_cloudy.png
  HistogramMatching/empire_state_sunset.png
  HistogramMatching/histogram.png
  HistogramMatching/match_histograms.ipynb
Labels: Level3, gssoc21

#89 BGR2GRAY Issue#25
  ChangeColorSpace/bgr2Gray.ipynb
  ChangeColorSpace/images/henry.jpg
Labels: Level3, gssoc21

#172 Shi Tomasi Corner Detection for issue #141
  Shi_Tomasi_CornerDetection/README.md
  Shi_Tomasi_CornerDetection/ShiTomasi.ipynb
  Shi_Tomasi_CornerDetection/flat_chessboard.png
  Shi_Tomasi_CornerDetection/real_ch.jpg
Labels: Level3, gssoc21

#171 Issue-154
  FastAlgorithm/FeaturesFromAcceleratedSegmentTestAlgorithm.ipynb
  FastAlgorithm/README.md
Labels: Level3, gssoc21

#181 Tracking APIs in OpenCV
  Tracking_API/README.md
  Tracking_API/Tracking_Apis.ipynb
Labels: Level3, gssoc21

#198 Fixed broken links in the readme file.
  README.md
Labels: Level0, gssoc21

#160 Image masking
  Image Masking/README.md
  Image Masking/mask.ipynb
  Image Masking/ppp
  OtsuThresholding/Otsu_Threshold.ipynb
  OtsuThresholding/README.md
Labels: Level3, gssoc21

#197 Added notebook and readme files for ORB Algorithm
  OrbAlgorithm/OrbAlgorithm.ipynb
  OrbAlgorithm/README.md
Labels: Level3, gssoc21

#211 Gaussian Filter
  ImageSmoothing/GaussianSmoothing/.ipynb_checkpoints/Gaussian_Filtering-checkpoint.ipynb
  ImageSmoothing/GaussianSmoothing/Gaussian_Filtering.ipynb
  ImageSmoothing/GaussianSmoothing/README.md
  ImageSmoothing/GaussianSmoothing/images/Gaussian_noise.jpg
  ImageSmoothing/GaussianSmoothing/images/Poission_noise.png
  ImageSmoothing/GaussianSmoothing/images/Salt&pepper_noise.png
  ImageSmoothing/GaussianSmoothing/images/Speckle_noise.jpg
  ImageSmoothing/GaussianSmoothing/images/gauss1.JPG
  ImageSmoothing/GaussianSmoothing/images/gauss2.JPG
  ImageSmoothing/GaussianSmoothing/images/gauss3.JPG
  ImageSmoothing/README.md
Labels: Level3, gssoc21

#202 Added implementation of BRIEF and edited the readme
  BriefAlgorithm/Brief.ipynb
  BriefAlgorithm/README.md
Labels: Level3, gssoc21

#205 Grab-cut algorithm
  Grab-Cut Algorithm/Grabcut.ipynb
  Grab-Cut Algorithm/README.md
Labels: Level3, gssoc21

#90 Partially fixed issue 27
  HarrisCornerDetection/Harris_Corner_Detection.ipynb
  HarrisCornerDetection/README.md
  HarrisCornerDetection/images/input.jpg
  HarrisCornerDetection/images/output.jpg
Labels: Level3, gssoc21

#173 Watershed Algorithm added
  WatershedAlgorithm/Images/Input_image.jpg
  WatershedAlgorithm/Images/Resultant_image.jpg
  WatershedAlgorithm/README.md
  WatershedAlgorithm/Watershed Algorithm.ipynb
Labels: Level3, gssoc21
